### ISSUE TITLE
features names added within data columns

### ISSUE THREAD

**Issue by MartinFXP** [dirmeier/rnai-utilities#8] opened 2017-06-13 14:32 UTC
It seems columns names are put in every couple of hundred rows or something.

```r
     gene <- "nfkb2"
     
     cells <- 10
     
     lib <- "d"
     
     script <- c("#!/usr/bin/env python3",
                 
                 "from rnaiquery import Query",

                 'q = Query("/net/bs-filesvr05/export/group/beerenwinkel/mpirkl/tix.db")',
                 
                 paste('res = q.query(library="', lib, '", featureclass="cells", gene="', gene, '", sample=', cells, ')', sep = ""),
                 
                 'res.dump("temp.tsv")')
     
     write(script, file = "temp.py")
     
     system("python temp.py")

     data <- read.delim("temp.tsv")
     
data[131, ]
```

Gives me the following output: (I did it twice and both times it was row 131)

```r
    study pathogen library design replicate plate well gene sirna well_type
131 study pathogen library design replicate plate well gene sirna well_type
    image_idx object_idx cells.areashape_area cells.areashape_eccentricity
131 image_idx object_idx cells.areashape_area cells.areashape_eccentricity
    cells.areashape_extent cells.areashape_formfactor
131 cells.areashape_extent cells.areashape_formfactor
    cells.areashape_majoraxislength cells.areashape_minoraxislength
131 cells.areashape_majoraxislength cells.areashape_minoraxislength
    cells.areashape_orientation cells.areashape_perimeter
131 cells.areashape_orientation cells.areashape_perimeter
    cells.children_bacteria_count cells.children_invasomes_count
131 cells.children_bacteria_count cells.children_invasomes_count
    cells.location_center_x cells.location_center_y
131 cells.location_center_x cells.location_center_y
    cells.neighbors_anglebetweenneighbors_2
131 cells.neighbors_anglebetweenneighbors_2
    cells.neighbors_firstclosestobjectnumber_2
131 cells.neighbors_firstclosestobjectnumber_2
    cells.neighbors_firstclosestxvector_2 cells.neighbors_firstclosestyvector_2
131 cells.neighbors_firstclosestxvector_2 cells.neighbors_firstclosestyvector_2
    cells.neighbors_numberofneighbors_2 cells.neighbors_percenttouching_2
131 cells.neighbors_numberofneighbors_2 cells.neighbors_percenttouching_2
    cells.neighbors_secondclosestobjectnumber_2
131 cells.neighbors_secondclosestobjectnumber_2
    cells.neighbors_secondclosestxvector_2
131 cells.neighbors_secondclosestxvector_2
    cells.neighbors_secondclosestyvector_2 cells.parent_nuclei
131 cells.neighbors_secondclosestyvector_2 cells.parent_nuclei
```

Is this done for a reason?

**Comment by dirmeier** [comment] 2017-06-13 14:59
Calling this

```python
  ...
  res=q.query(featureclass="cells", gene="nfkb2", library="d")
  res.dump("temp.tsv")
```
gives me the following:

```sh
  $ grep study temp.tsv | wc -l
  1
```

So I am not able to reproduce this. Is it possible you called this twice? Since we are iterating over many plates, we are always appending to the same filehandle. That means, if the file already existed and you call `dumb` then its not deleted but the new lines are added to the previous ones. This has the advantage that i can partition the writing process and am able to at any time add new plates to an existing file. Might this be the problem?

**Comment by MartinFXP** [comment] 2017-06-13 15:19
```
In [1]: from rnaiquery import Query

In [2]: q = Query('/net/bs-filesvr05/export/group/beerenwinkel/mpirkl/tix.db')

In [3]: res = q.query(library='d', featureclass='cells', gene='nfkb2', sample=1)
[INFO/MainProcess/rnaiquery.dbms._sqlite_connection]: Connecting to sqlitr db
[INFO/MainProcess/rnaiquery.dbms._db_query]: 
SELECT * 
	FROM (SELECT * FROM meta WHERE library='d' and featureclass='cells') a1 
	JOIN (SELECT filename FROM gene WHERE gene='nfkb2') a2 
	ON (a1.filename = a2.filename);
[INFO/MainProcess/rnaiquery.dbms._database_connection]: Closing connection to db

In [4]: res.dump('temp2.tsv')
[INFO/MainProcess/rnaiquery.io.io]: Writing to tsv 
[INFO/MainProcess/rnaiquery.result_set]: Successfully wrote table files!

In [5]: 

In [5]: res = q.query(library='d', featureclass='cells', gene='nfkb2', sample=10)
[INFO/MainProcess/rnaiquery.dbms._sqlite_connection]: Connecting to sqlitr db
[INFO/MainProcess/rnaiquery.dbms._db_query]: 
SELECT * 
	FROM (SELECT * FROM meta WHERE library='d' and featureclass='cells') a1 
	JOIN (SELECT filename FROM gene WHERE gene='nfkb2') a2 
	ON (a1.filename = a2.filename);
[INFO/MainProcess/rnaiquery.dbms._database_connection]: Closing connection to db

In [6]: res.dump('temp2.tsv')
[INFO/MainProcess/rnaiquery.io.io]: Writing to tsv 
[INFO/MainProcess/rnaiquery.result_set]: Successfully wrote table files!
```
```
bs-mbpr189:mpirkl$ mpirkl$ grep study temp2.tsv | wc -l
       2
```
Is res.dump appending? Apart from that I was playing around with the sample parameter and am getting weird results. I'll have a deeper look into that and might report in another issue. However, the two could be related.

**Comment by dirmeier** [comment] 2017-06-13 19:36
See my previous comment:

> Since we are iterating over many plates, we are always appending to the same filehandle. That means, if the file already existed and you call dump then its not deleted but the new lines are added to the previous ones.

I added an exception is this scenario though.

**Comment by dirmeier** [comment] 2017-06-14 13:20
Can I close this?

**Closed** 2017-06-14 14:28 UTC
